#include <iostream>
#include <fstream>
#include <sstream>
#include "lexer.h"
#include "parser.h"
#include "interpreter.h"
#include "analyzer.h"

using namespace std;

void processAndShow(string input){

        vector<Token> tokens;

        try {
            tokens = tokenize(input);
        } catch (runtime_error& e) {
            cerr << "Error lexico: " << e.what() << endl;
            return;
        }

        ParseResult parsed;

        try {
            parsed = parse(tokens);
        } catch (runtime_error& e) {
            cerr << "Error sintactico: " << e.what() << endl;
            return;
        }

        if (parsed.program == nullptr) {
            cerr << "Error: el programa esta vacio." << endl;
            return;
        }

        if (parsed.program->rules.empty()) {
            cerr << "Error: no se encontraron reglas en el programa." << endl;
            return;
        }

        set<string> activatedFacts = interpret(
            parsed.program,
            parsed.variables,
            parsed.facts
        );

        AnalysisResult analysis = analyze(
            parsed.program,
            parsed.variables,
            parsed.facts);

        cout << "  Output:                           " << endl;

        if (activatedFacts.empty()) {
            cout << "(no output)" << endl;
        } else {
            for (const string& fact : activatedFacts) {
                cout << fact << endl;
            }
        }

        bool hasAnalysis = !analysis.conflicts.empty()    ||
                          !analysis.redundancies.empty() ||
                          !analysis.inactiveRules.empty();

        if (hasAnalysis) {
            cout << endl;
            cout << "Analysis:" << endl;

            for (auto& entry : analysis.conflicts) {
                cout << "Action " << entry.first << " generated by ";
                vector<string>& rules = entry.second;
                for (int i = 0; i < (int)rules.size(); i++) {
                    cout << rules[i];
                    if (i < (int)rules.size() - 1) cout << ", ";
                }
                cout << endl;
            }
            for (auto& group : analysis.redundancies) {
                cout << "Redundant rules: ";
                for (int i = 0; i < (int)group.size(); i++) {
                    cout << group[i];
                    if (i < (int)group.size() - 1) cout << ", ";
                }
                cout << endl;
            }
            for (const string& ruleName : analysis.inactiveRules) {
                cout << "Potentially inactive rule: "
                     << ruleName << endl;
            }
        }
    }


int main() {
    while (true) {
        string input;
        cout << " "<< endl;
        cout << "Hello, welcome to the Rule-Based Language Interpreter " << endl;
        cout << "How do you want to insert the lenguage?" << endl;
        cout << "  1. Type or paste into the console"   << endl;
        cout << "  2. Load it from a .txt file"   << endl;
        cout << "  3. Exit the program"   << endl;
        cout << "Your choice: ";
        int option;
        cin >> option;
        if (option == 1) {
            cout << endl;
            cout << "Write or copy the program." << endl;
            cout << "When finish, tap Enter and write '---' in the new line"<< endl;
            string line;
            stringstream buffer;

            while (getline(cin, line)) {
                if (line == "---") break;
                buffer << line << "\n";
            }
            input = buffer.str();
        } else if (option == 2) {
            cout << "Write the path of your file: ";
            string filepath;
            getline(cin, filepath);
            ifstream file(filepath);

            if (!file.is_open()) {
                cerr << "Error: the file could not be opened '"
                     << filepath << "'" << endl;
            }

            stringstream buffer;
            buffer << file.rdbuf();
            input = buffer.str();
            file.close();

            cout << "File loaded successfully" << endl;

        } else if (option == 3) {
            cout << "You have exited the program ";
            break;
        }
        else {
            cerr << "Invalid option, please choose 1, 2 or 3" << endl;
        }
        processAndShow(input);
    }
}